import { default_completion_model, models, getDefaultModelParams } from "@pufflig/ps-models";
import { NodeConfig } from "@pufflig/ps-types";

export const llmCompletionNodeType = "adapter/llm_completion" as const;

export const llmCompletionConfig: NodeConfig = {
  name: "Instruction",
  description: "Generate a completion using an LLM",
  status: "stable",
  tags: ["adapter", "text"],
  globals: [],
  execution: {
    inputs: [
      {
        id: "exec:input",
      },
    ],
    outputs: [
      {
        id: "exec:output",
        name: "Completed",
      },
    ],
  },
  outputs: [
    {
      id: "completion",
      name: "Completion",
      description: "Text generated by the LLM",
      type: "text",
      defaultValue: "",
    },
  ],
  inputs: [
    {
      id: "model",
      name: "AI Settings",
      description: "The model to use",
      type: "model",
      definition: models,
      defaultValue: {
        modelId: default_completion_model,
        parameters: getDefaultModelParams(default_completion_model),
      },
    },
    {
      id: "prompt",
      name: "Prompt",
      description: "The prompt to send to the LLM",
      type: "text",
      defaultValue: "",
    },
  ],
};
